### ISSUE TITLE
'igl/copyleft/cgal/segment_segment_intersect.h' file not found while compiling

### ISSUE THREAD

**Issue by duxingyi-charles** [hankstag/progressive_embedding#1]
It seems this project depends on a history version of libigl, which is different from the current libigl.

### Error message produced by "make":

/Users/charlesdu/Downloads/research/progressive_embedding/is_simple_polygon.cpp:10:10: fatal error:
      'igl/copyleft/cgal/segment_segment_intersect.h' file not found
#include <igl/copyleft/cgal/segment_segment_intersect.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/shor_van_wyck.dir/is_simple_polygon.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/Users/charlesdu/Downloads/research/progressive_embedding/shor.cpp:7:10: fatal error:
      'igl/copyleft/cgal/ear_clipping.h' file not found
#include <igl/copyleft/cgal/ear_clipping.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/shor_van_wyck.dir/shor.cpp.o] Error 1
make[1]: *** [CMakeFiles/shor_van_wyck.dir/all] Error 2
make: *** [all] Error 2

**Comment by jiangzhongshi** [comment]
There are a few files not yet integrated into the main repository (I guess PR are pending). But you can find the corresponding files from https://github.com/hankstag/libigl/tree/Shor/include/igl/copyleft/cgal

**Comment by duxingyi-charles** [comment]
Thanks, now the compiling is successful
